project:
  type: website
  output-dir: docs

website:
  title: "Adventures in Spain"
  site-url: "https://mattbixley.github.io/spain/"
  repo-url: "https://github.com/MattBixley/spain"
#  repo-actions: [edit, issue]
  open-graph: true

  page-footer: 
    left: "© {{< now year >}} Matt Bixley "
    right: 
      - "Built with Quarto and Github"
      - icon: github
        href: https://github.com/MattBixley/spain

  navbar:
    left:
      - href: index.qmd
        text: Home
#     - about.qmd
      - href: posts.qmd
        text: Diary of Spain
      - href: gallery.qmd
        text: Gallery
      - href: maps.qmd
        text: Maps

format:
  html:
    theme: [slate, custom.scss]
 #   mainfont: "montserrat"
    toc: true
    
editor: visual

