project:
  type: website
  output-dir: docs

website:
  title: "spain"
  site-url: "https://mattbixley.github.io/spain/"
  repo-url: "https://github.com/MattBixley/spain"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - posts.qmd
      - gallery/gallery.qmd
    right:
      - icon: github
        href: https://github.com/MattBixley/spain

format:
  html:
    theme: slate
#   mainfont: "montserrat"
    css: styles.css
    toc: true
    
editor: visual

