project:
  type: website
  output-dir: docs

website:
  title: "spain"
  site-url: "https://mattbixley.github.io/spain/"
  repo-url: "https://github.com/MattBixley/spain"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - href: posts.qmd
        text: Diary of Spain
      - href: gallery/gallery.qmd
        text: Gallery
      - href: maps/maps.qmd
        text: Maps
        
    right:
      - icon: github
        href: https://github.com/MattBixley/spain

format:
  html:
    theme: [slate, styles.css]
 #   mainfont: "montserrat"
    toc: true
    
editor: visual

