project:
  type: website
  output-dir: docs

website:
  title: "spain"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
      - posts.qmd
      - gallery/gallery.qmd

format:
  html:
    theme: slate
#   mainfont: "montserrat"
    css: styles.css
    toc: true
    
editor: visual

