---
title: "Madrid"
description: Travel and a couple of days in MAdrid
  
author: Matt Bixley
date: 2025-07-06
categories: Madrid, Food
---

A trip that was 3 years in the planning. In 2022 Spain was awarded the World Rogaining Championships which I wiulkd need to attend if still President of the International Rogaining Federation so planning and saving began......\
\
Hola - we now live in Spain for 2 months.

### Leg 1

Booking was a drama, flights are a lot more expensive than they used to be so I reverted to an agent but consequently had to cope with a 1st leg Jetstar flight...... House sitter in place we kicked off with a drive to Christchurch, dinner with Sam and Ollie, donating a car to the newly minted restricted licensee Samantha and a successful ealry morning flight to Auckland

### Leg 2

Cathay Pacific: Auckland - Hong Kong - Madrid\
Both are longish and the lounge we went to in Hong Kong was at best, abysmal. I don't really sleep on planes, so 5ish movies, some naps, some walking, half a migraine and we are in Spain

### Leg 3

Madrid Customs: I think 2 flights landed about the same time, 2 agents for the EU passport holders and **ONE** for the rest of us **ONE....** We thought one little 737 into Dunedin and taking an hour for customs was amusing a few years ago. Eventually they upped the Customs OFicer total to 4 and allowed everyone to use all the lanes. Still over and hour to clear customs. Then find bags which it turned out were a 5 minute train ride away.\
\
All while we are waiting I'm trying to get stable wifi or my sim card working on a brand new phone of the type I refused to ever buy but work merger has forced upon me the dreaded iPhone. So unsure how to get to Hotel, can;t source maps or bus timetables or bus numbers...nothing. So stress is setting in on top of fatigue. Get random short bursts of wifi and order and restart UBER app, panic to find UBER pickup location. Give Luis 5 stars because he dropped us at the hotel door and panic/anxiety has gone.\
\
11:30am and hotel amazingly let us check in. Shower, Nap. IT'S HOT, landed to a European Heatwave and we go from single digit Dunedin to 39 degrees.\
\
\### Vuelta a Madrid\
\
\
\
